@ECHO OFF
@ECHO Executing: %~f0

SETLOCAL
SET CURRENT_PATH=%~dp0
CALL %CURRENT_PATH%Env.bat

IF EXIST %ALLURE_REPORT% (
    rmdir %ALLURE_REPORT% /s /q
)

SET CMD=%ALLURE_EXE% generate %ALLURE_RESULTS% --output %ALLURE_REPORT%
ECHO Generate report from %ALLURE_RESULTS% to %ALLURE_REPORT%
ECHO %CMD%
CALL %CMD%

SET CMD=%ALLURE_EXE% open %ALLURE_REPORT%
ECHO Open report from %ALLURE_REPORT%
ECHO %CMD%
CALL %CMD%
ENDLOCAL