@ECHO OFF
@ECHO Executing: %~f0

SETLOCAL
SET CURRENT_PATH=%~dp0
CALL %CURRENT_PATH%Env.bat

SET CMD=START %EXTENT_REPORT_PATH%
ECHO Generate report from %ALLURE_RESULTS% to %ALLURE_REPORT%
ECHO %CMD%
CALL %CMD%

ENDLOCAL