@ECHO OFF

SET CURRENT_PATH=%~dp0
SET WORKSPACE=%CURRENT_PATH%..

SET BUILD_PATH=%WORKSPACE%\build

SET ALLURE_EXE=%WORKSPACE%\allure-commandline-2.13.9\bin\allure.bat
SET ALLURE_BIN=%WORKSPACE%\allure-commandline-2.13.9\bin\
SET ALLURE_RESULTS=%WORKSPACE%\allure-results
SET ALLURE_REPORT=%WORKSPACE%\allure-report
