@ECHO OFF

SET CURRENT_PATH=%~dp0
SET WORKSPACE=%CURRENT_PATH%..

SET BUILD_PATH=%WORKSPACE%\build

SET ALLURE_EXE=%WORKSPACE%\allure-commandline-2.13.9\bin\allure.bat
SET ALLURE_RESULTS=%BUILD_PATH%\allure-results
SET ALLURE_REPORT=%BUILD_PATH%\allure-report
